# config.ini
# This file is used to store application configuration details
# such as URL, browser, wait time, and login credentials.
# It helps avoid hardcoding values inside the test scripts
# and makes the framework easier to maintain.

[settings]
base_url = https://adnabu-store-assignment1.myshopify.com/password
browser = chrome

[credentials]
password = AdNabuQA